
##################################
## Discovery and identification ##
##################################

title: # Title of dataset to be inserted here
summary: # Short summary of dataset

keywords: # keywords that further explains dataset provided as list: ['keyword 1', 'keyword 2', ..., 'keyword N']
          # keywords ideally should be sources from an established/community-driven vocabulary of terms
keywords_vocabulary: # in case when keywords are sources from restricted vocabularies it is advisable to
                     # provide a list of URI's to the restricted vocabularies from where the keywords are sourced,
                     # e.g.: ['http://cfconventions.org/Data/cf-standard-names/71/build/cf-standard-name-table.html', 'http://data.windenergy.dtu.dk/taxonomy/']

dataset_id: # unique and persistent identifier of dataset, it could be for example DOI
dataset_id_authority: # an URI of the authority body that generated dataset_id (this is optional metadata)

infrastructure_id: # a list of PIDs (could be URIs) to virtual (models, HPC) or physical (instruments) infrastructure(s) which generated dataset
site: # location where data was created, this is mandatory only for measurements datasets otherwise it can be dropped

creator_name: # an ordered list of FirstName LastName of those whose created the dataset (order according to the level of contributions)
creator_email: # an ordered list of creators' email addresses
creator_id: # an order list of creators' ORCID IDs, if IDs are missing input empty string
creator_role: # an order list of specific roles contributor had in the dataset creation
              # roles are described by CredIT taxonomy: https://like-itn-digitalization.readthedocs.io/en/latest/1_research_lifecycle/#roles-in-lifecycle

contributor_name: # an ordered list of FirstName LastName of those whose contributor to the creation of dataset (order according to the level of contributions)
contributor_email: # an ordered list of contributor email addresses
contributor_id: # an order list of contributor ORCID IDs, if IDs are missing input empty string
contributor_role: # an order list of specific roles contributor had in the dataset creation
                  # roles are described by CredIT taxonomy: https://like-itn-digitalization.readthedocs.io/en/latest/1_research_lifecycle/#roles-in-lifecycle

project_name: # a list of projects which provided funding for the dataset generation
project_id: # a list of project numbers which are identifiable in for example OpenAIER
            # this list is ordered according project_name metadata
            # alternatively it could be a resolvable URIs to say landing pages of the project

## Optional metadata


authors : 'Pedro Santos, Gancarski Paweł'
license : 'Creative Commons Attribution 4.0'

institution_edmo_code         : '4975' #EDMO id for your institution can be found here - https://edmo.seadatanet.org/search
institution                   : 'CENER'
institution_references        : 'http://www.cener.com/'
comment                       : 'Merged observation files based on data generated by Pedro Santos paas@dtu.dk'
date_update                   : '2020-05-09T15:30:00Z'
history                       : '2020-05-09T15:30:00Z Creation'

################################## End update this section

################################# Discovery and identification
# Optional


################################# Geo-spatial-temporal
data_type     : 'ALEX17 Diurnal Cycles Benchmark'
time_coverage_start : '2018-09-30T00:00:00Z'
time_coverage_end : '2018-10-04T00:00:00Z'
area          : 'Spain'

################################# Conventions used
format_version     : '1.X'
Conventions        : 'CF'
netcdf_version : 'netCDF-4'

################################# Publication information
# Optional
references       : ''
data_center      : ''
update_interval  : 'void'
citation         : ''
doi              : ''
