###############################################################################
######################## Discovery and identification #########################
###############################################################################


# To identify dataset you need to provide a unique & persistent identifier(PID).
# The most obvious candidate for dataset PID is DOI.
# A way to obtain it prior publishing your dataset is to make a DOI reservation.
# Then simply insert the reserved DOI here.
# PIDs should be resolvable.
# Attribute: mandatory
# Input type: fixed resolvable PID
dataset_id: ''

# An URI of the authority body that generated dataset_id
# Attribute: recommended
# Input type: fixed resolvable URI
dataset_id_authority: ''

# If dataset is a part of larger data collection is_part_of provides the
# link to the collection. For example, data collection will have PID, such as
# DOI. Therefore, is_part_of will contain that PID.
# Attribute: recommended
# Input type: fixed resolvable PID
is_part_of: ''

# If the entire dataset is split to multiple files into multiple files
# is_related_to holds ids of remaining files which make dataset complete.
# The ids of remaining files could be simple as file names.
# Attribute: mandatory (if dataset is split to multiple files)
# Input type: fixed resolvable PIDs
is_related_to: ['']

# Dataset is generated wither using virtual (models) or physical(instruments)
# infrastructures. Accordingly, it is always a good practice to indicate
# what infrastructure was used to generate the dataset.
# infrastructure_id should contain a list of ids of the used infrastructures.
# The ids could be for example URLs to the instruments.
# Attribute: optional
# Input type: free text or fixed resolvable URIs/PIDs
infrastructure_id: ['']


# Provide a list of people who take a part in data creation.
# List them according to the priority as FirstName LastName.
# Attribute: mandatory
# Input type: free text
creator_name: ['Gancarski, Paweł']

# Provide a list of emails of data creators. The list elements must follow
# the order of creators' names.
# Attribute: mandatory
# Input type: free text
creator_email: ['pgancarski@cener.com']

# Since people to tend to change their positions or jobs email addresses tend
# to be obsolete. To maintain a possibility of contacts a much more persistent
# approach is to provide ORCiD ids of creators.
# Attribute: recommended
# Input type: fixed resolvable PID
creator_id: ['https://orcid.org/0000-0001-9198-8429']

# List of creator names don't tell us much about who done what in the process
# of data creation. creator_role provides a means to highlight a particular
# role(s) each data creator had. The roles could be described using CredIT
# taxonomy:
# https://like-itn-digitalization.readthedocs.io/en/latest/1_research_lifecycle/#roles-in-lifecycle
# Attribute: optional
# Input type: free text or terms from controlled vocabulary
creator_role: ['Data curation']


# Provide a list of people who contributed to data creation, but where not
# sufficient contributors to be seen as data creators.
# List them according to the priority as FirstName LastName.
# Attribute: recommended
# Input type: free text
contributor_name: ['']

# Same as creator_email
# Attribute: recommended
# Input type: free text
contributor_email: ['']

# Same as creator_id
# Attribute: recommended
# Input type: fixed resolvable PIDs
contributor_id: ['']

# Same as creator_role
# Attribute: optional
# Input type: free text or terms from controlled vocabulary
contributor_role: ['']


###############################################################################
########################### Publication information ###########################
###############################################################################

# Licence that specifies usage of dataset. You must provide the license since
# without it end-users do not have information on how they can use your data.
# You could provide a full text of license, which would be a case if your
# dataset has a special data usage license. However, in majority of cases you
# will use Create Commons license, which in this case you can provide the
# license name (e.g., CC BY 4.0 International).
# Alternately, provide a URL to the license.
# Attribute: mandatory
# Input type: text defined by license, license ID or license URL
license: 'Creative Commons Attribution 4.0'

# Notation that marks dataset according to its security classification to ensure
# it is circulated only among the authorized recipients.
# Potentially the distribution statement could look like this:
# Statement A: Approved for public release; distribution is unlimited.
#
# Statement B: Approved for public release; distribution is defined by license.
#
# Statement C: Distribution authorized to (insert authorized entities) only;
# (fill in reason); (date of determination). Other requests for this document
# shall be referred to (insert controlling government office).
#
# Statement D: Distribution authorized to (insert authorized entities) and
# their contractors; (fill in reason); (date of determination). Other requests
# for this document shall be referred to (insert controlling government office).
#
# Attribute: optional
# Input type: free text
distribution_statement: 'Approved for public release; distribution is defined by license.'

# The data publisher's name. The publisher may be an individual or an institution.
# Attribute: mandatory
# Input type: free text
publisher_name: ''

# The data publisher's email.
# The publisher email may be an individual or of an institution.
# Attribute: recommended
# Input type: free text
publisher_email: ''

# The data publisher's url.
# The publisher may be an individual or an institution.
# Attribute: recommended
# Input type: free text
publisher_url: ''

# The citation to be used in publications using the dataset.
# The explicit text stating how to cite the dataset.
# Attribute: optional
# Input type: free text
citation: ''


